import os
from datetime import datetime
from src.config import OUTPUT_DIR, SITE_CONFIG
from src.aggregator import load_all


def esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def render_card(item: dict) -> str:
    url = esc(item.get("url", "#"))
    title = esc(item.get("title") or item.get("name", ""))
    desc = esc((item.get("description") or "")[:250])
    source = esc(item.get("source", ""))

    parts = []
    if source:
        parts.append(f'<span class="tag">{source}</span>')
    authors = item.get("authors")
    if authors:
        parts.append(f'<span class="meta">{" · ".join(authors[:3])}</span>')
    published = item.get("published", item.get("updated_at", ""))
    if published:
        try:
            d = datetime.fromisoformat(published.replace("Z", "+00:00"))
            parts.append(f'<span class="meta">{d.strftime("%Y-%m-%d")}</span>')
        except Exception:
            pass
    stars = item.get("stars", item.get("likes", item.get("downloads", 0)))
    if stars:
        parts.append(f'<span class="meta">&#9733; {stars}</span>')
    tag = item.get("pipeline_tag", "")
    if tag:
        parts.append(f'<span class="tag">{esc(tag)}</span>')

    topics_html = ""
    topics = item.get("topics", item.get("tags", []))
    if topics:
        topic_spans = "".join(f"<span>{esc(str(t))}</span>" for t in topics[:4])
        topics_html = f'<div class="topics">{topic_spans}</div>'

    meta = "".join(parts)

    return (
        f'<a href="{url}" target="_blank" rel="noopener" class="card">'
        f'<div class="card-body">'
        f'<h3 class="card-title">{title}</h3>'
        f'<p class="card-desc">{desc}</p>'
        f'{topics_html}'
        f'<div class="card-meta">{meta}</div>'
        f"</div></a>"
    )


def render_section(icon: str, title: str, items: list[dict], color: str) -> str:
    if not items:
        return ""
    cards = "\n".join(render_card(it) for it in items)
    n = len(items)
    return (
        f'<section class="section">'
        f'<h2 class="section-title" style="border-left:4px solid {color};padding-left:12px">'
        f'<span class="section-icon">{icon}</span> {title}'
        f'<span class="item-count">{n}</span></h2>'
        f'<div class="cards">{cards}</div>'
        f"</section>"
    )


def generate_site():
    data = load_all()
    now = datetime.utcnow()

    html_parts = []
    a = html_parts.append

    a("<!DOCTYPE html>")
    a('<html lang="zh-CN">')
    a("<head>")
    a('<meta charset="UTF-8">')
    a('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
    a(f"<title>{esc(SITE_CONFIG['title'])}</title>")
    a(f"<meta name='description' content='{esc(SITE_CONFIG['description'])}'>")
    a("<style>")
    a(CSS)
    a("</style>")
    a("</head>")
    a("<body>")
    a('<div class="container">')
    a("<header>")
    a(f"<h1>{esc(SITE_CONFIG['title'])}</h1>")
    a(f'<p class="sub">{esc(SITE_CONFIG["description"])}</p>')
    a('<div class="meta-bar">')
    a(f"<span>&#128197; {now.strftime('%Y-%m-%d %H:%M UTC')}</span>")
    a("<span>&#128202; <span id='item-count'>0</span> items</span>")
    a("<span>&#128260; Auto-updates daily via GitHub Actions</span>")
    a("</div>")
    a("</header>")
    a("<main>")

    sections = [
        ("hf_papers", "\U0001f4c4", "AI \u8bba\u6587 \u00b7 Hugging Face Daily Papers", "#6366f1"),
        ("arxiv", "\U0001f4da", "arXiv \u6700\u65b0\u8bba\u6587", "#8b5cf6"),
        ("github_trending", "\U0001f525", "\u70ed\u95e8 AI \u5f00\u6e90\u9879\u76ee \u00b7 GitHub Trending", "#22c55e"),
        ("hf_models", "\U0001f916", "\u65b0\u5f00\u6e90\u6a21\u578b \u00b7 Hugging Face Models", "#f59e0b"),
        ("rss_news", "\U0001f4f0", "AI \u884c\u4e1a\u65b0\u95fb", "#3b82f6"),
    ]

    total = 0
    for key, icon, title, color in sections:
        items = data.get(key, [])
        total += len(items)
        a(render_section(icon, title, items, color))

    a("</main>")
    a("<footer>")
    a("<p>Generated by AI News Hub &middot; Data from Hugging Face, arXiv, GitHub, RSS</p>")
    a("</footer>")
    a("</div>")
    a('<script>document.getElementById("item-count").textContent = "' + str(total) + '";</script>')
    a("</body>")
    a("</html>")

    html = "\n".join(html_parts)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    path = os.path.join(OUTPUT_DIR, "index.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"\n[site_generator] Site generated: {path} ({len(html)} bytes, {total} items)")
    return path


CSS = """\
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--bg:#f8fafc;--surface:#ffffff;--text:#1e293b;--text2:#64748b;--border:#e2e8f0;--card-hover:#f1f5f9;--shadow:0 1px 3px rgba(0,0,0,.08),0 1px 2px rgba(0,0,0,.06);--radius:12px}
@media(prefers-color-scheme:dark){:root{--bg:#0f172a;--surface:#1e293b;--text:#f1f5f9;--text2:#94a3b8;--border:#334155;--card-hover:#334155;--shadow:0 1px 3px rgba(0,0,0,.3)}}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans SC",sans-serif;background:var(--bg);color:var(--text);line-height:1.6;min-height:100vh}
.container{max-width:1200px;margin:0 auto;padding:0 20px}
header{padding:40px 0 24px;border-bottom:1px solid var(--border);margin-bottom:32px}
header h1{font-size:32px;font-weight:800;letter-spacing:-0.5px;background:linear-gradient(135deg,#6366f1,#8b5cf6,#ec4899);-webkit-background-clip:text;-webkit-text-fill-color:transparent}
header .sub{color:var(--text2);font-size:15px;margin-top:6px}
header .meta-bar{display:flex;gap:16px;margin-top:12px;font-size:13px;color:var(--text2);flex-wrap:wrap}
header .meta-bar span{display:flex;align-items:center;gap:4px}
.section{margin-bottom:40px}
.section-title{font-size:20px;font-weight:700;margin-bottom:16px;display:flex;align-items:center;gap:8px}
.section-icon{font-size:22px}
.item-count{margin-left:auto;font-size:12px;font-weight:600;background:var(--border);padding:2px 10px;border-radius:20px;color:var(--text2)}
.cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(340px,1fr));gap:12px}
.card{display:block;text-decoration:none;color:inherit;background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:16px;transition:all .2s;box-shadow:var(--shadow)}
.card:hover{background:var(--card-hover);transform:translateY(-2px);box-shadow:0 4px 12px rgba(0,0,0,.12)}
.card-title{font-size:15px;font-weight:600;line-height:1.4;margin-bottom:6px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
.card-desc{font-size:13px;color:var(--text2);line-height:1.5;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden;margin-bottom:8px}
.card-meta{display:flex;flex-wrap:wrap;gap:6px;align-items:center;font-size:12px;color:var(--text2)}
.card-meta .tag{background:var(--border);padding:1px 8px;border-radius:4px;font-size:11px;font-weight:500}
.card-meta .meta{opacity:.8}
.topics{display:flex;flex-wrap:wrap;gap:4px;margin-bottom:8px}
.topics span{font-size:11px;background:rgba(99,102,241,.1);color:#6366f1;padding:1px 8px;border-radius:4px}
footer{text-align:center;padding:32px 0;border-top:1px solid var(--border);color:var(--text2);font-size:13px;margin-top:16px}
@media(max-width:640px){.cards{grid-template-columns:1fr}header h1{font-size:26px}}
"""


if __name__ == "__main__":
    generate_site()
